"""
agents/report_agent.py

Report Agent responsible for:

- Fetching analytics data
- Generatin structured business reports
- Exporting reports (TXT, CSV, JSON)
- Saving reports to reports directory

Works with SQLAgent for data retrieval.

Author: Hariom Patidar
"""

import json
import csv
from datetime import datetime
from pathlib import Path

from agents.sql_agent import sql_agent
from config import REPORTS_DIR, DEFAULT_REPORT_FORMAT
import logging


class ReportAgent:
    """
    ReportAgent generates business reports automatically
    using SQLAgent outputs.
    """

    def __init__(self):
        self.sql_agent = sql_agent


    # =========================
    # FETCH WEEKLY REVENUE DATA
    # =========================

    def fetch_weekly_revenue(self):
        """
        Fetch last 7 days revenue using SQLAgent.
        """

        logging.info("Fetching weekly revenue data")

        response = self.sql_agent.run("last week revenue")

        return response


    # =========================
    # BUILD REPORT CONTENT
    # =========================

    def build_report(self, data):
        """
        Converts raw SQLAgent response into structured report text.
        """

        logging.info("Building structured report")

        if data["status"] != "success":
            return "Report generation failed."

        rows = data["result"]["rows"]

        if not rows:
            return "No data available for report."

        revenue = rows[0].get("weekly_revenue", "N/A")

        report_text = f"""
WEEKLY BUSINESS REPORT
======================

Generated On: {datetime.now()}

Key Metrics:
------------
Total Weekly Revenue: {revenue}

System Notes:
-------------
This report was automatically generated by Autonomous Workflow Bot.
"""

        return report_text


    # =========================
    # SAVE TXT REPORT
    # =========================

    def save_txt_report(self, report_text):
        """
        Saves report as TXT file.
        """

        filename = f"weekly_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"

        filepath = Path(REPORTS_DIR) / filename

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report_text)

        logging.info(f"TXT report saved: {filepath}")

        return str(filepath)


    # =========================
    # SAVE JSON REPORT
    # =========================

    def save_json_report(self, data):
        """
        Saves report as JSON file.
        """

        filename = f"weekly_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"

        filepath = Path(REPORTS_DIR) / filename

        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4)

        logging.info(f"JSON report saved: {filepath}")

        return str(filepath)


    # =========================
    # SAVE CSV REPORT
    # =========================

    def save_csv_report(self, rows):
        """
        Saves report as CSV file.
        """

        filename = f"weekly_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"

        filepath = Path(REPORTS_DIR) / filename

        if not rows:
            return None

        keys = rows[0].keys()

        with open(filepath, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=keys)
            writer.writeheader()
            writer.writerows(rows)

        logging.info(f"CSV report saved: {filepath}")

        return str(filepath)


    # =========================
    # MAIN REPORT PIPELINE
    # =========================

    def generate_weekly_report(self, format_type=DEFAULT_REPORT_FORMAT):
        """
        Full weekly report generation pipeline.
        """

        logging.info("Starting weekly report generation pipeline")

        data = self.fetch_weekly_revenue()

        if data["status"] != "success":
            return data

        rows = data["result"]["rows"]

        if format_type == "txt":

            report_text = self.build_report(data)

            filepath = self.save_txt_report(report_text)

        elif format_type == "json":

            filepath = self.save_json_report(rows)

        elif format_type == "csv":

            filepath = self.save_csv_report(rows)

        else:

            return {
                "status": "error",
                "message": "Unsupported report format"
            }

        return {
            "status": "success",
            "file": filepath,
            "format": format_type
        }


# =========================
# GLOBAL REPORT AGENT INSTANCE
# =========================

report_agent = ReportAgent()